version: '2'
services:
  jupyter:
    image: tensorflow/tensorflow:1.4.0-rc1-devel-py3
    container_name: jupyter
    ports:
      - 8888:8888
    environment:
      - 'PASSWORD=${password}'
    volumes:
      - "${log_dir}"
    command:
      - "/run_jupyter.sh"
      - "--allow-root"
  tensorboard:
    image: tensorflow/tensorflow:1.4.0-rc1-devel-py3
    container_name: tensorboard
    ports:
      - 6006:6006
    volumes_from:
      - jupyter
    command: 
      - 'tensorboard'
      - '--logdir'
      - '${log_dir}'
      - '--host'
      - '0.0.0.0'
    labels:
      io.rancher.sidekicks: jupyter